### ISSUE TITLE
Incorrect parsing of some font names.

### ISSUE THREAD

**Issue by Ulyanov-programmer** [tom2strobl/parse-font-name#2]
During the operation of your library, it turned out that when parsing some font names, incorrect values are returned as a result.

This reaction occurs in these cases:

- `centurygothic_bold` expected => `700 normal` exit => `400 normal`
- `MYRIADPRO-BOLDCONDIT` expected => `700 italic` exit => `400 normal`
- `MYRIADPRO-CONDIT` expected => `400 italic` exit => `400 normal`
- `MYRIADPRO-SEMIBOLD` expected => `600 normal` exit => `400 normal`
- `MYRIADPRO-SEMIBOLDIT` expected => `600 italic` exit => `400 normal`
- `MyriadPro CondIt` expected => `400 italic` exit => `400 normal`
- `alegreya-v29-latin-500` expected => `500 normal` exit => `400 normal`
- `alegreya-v29-latin-500italic` expected => `500 italic` exit => `400 italic`

Testing was carried out on the latest version of the library downloaded from NPM.

**Comment by tom2strobl** [comment]
thanks for the additional test @Ulyanov-programmer, appreciate it!

Three of them can be straight up classified as bugs, eg. the first one and the two MYRIAD bold and semibolds.

The cases where there are numeric Weights already in the filename are pretty interesting, I think we want to support that if no other weight could be determined from the name, will take a look.

I'm afraid the cases where the **"IT"** in the filename should be parsed as italics is too much of a slippery slope as "IT" could also be a part of the familyname and yield false positives.

Regarding the former I'll take a stab and get back to you.

**Comment by tom2strobl** [comment]
I just released a new version `1.2.0` that fixes weight recognition for all of the above mentioned cases and introduces matching of numeric weights in filenames. It will still prefer string recognition before matching X00 numbers in the filenames. The reason we prefer string matches over numeric values is that it's easy to have a typo on a single digit and more unlikely to accidentally have "Regular" in a filename. Also there could be triple digits in the actual font family name like "Nimbus500-Regular.ttf". But the current implementation will catch your `alegreya-v29-latin-500` case.

The **"IT"** is something we can't really fix without false positives, but if you happen to find any other cases your reports are very welcome!

**Comment by Ulyanov-programmer** [comment]
Some of the cases really were actually the result of a bug (which occurred several times) and did not manifest after the update.

Thank you for the work!
